#############################################################################
# Makefile for building: Capturas
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Apr 22 18:34:08 2013
# Project:  Capturas.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Capturas.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -pthread -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -pthread -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I/usr/local/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lopencv_core -lopencv_video -lopencv_imgproc -pthread -L/usr/local/lib -lprotobuf -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cvmatandqimage.cpp \
		main.cpp \
		imagineviewerwindow.cpp \
		procesadora.cpp Mensaje.pb.cc \
		moc_imagineviewerwindow.cpp \
		moc_procesadora.cpp
OBJECTS       = cvmatandqimage.o \
		main.o \
		imagineviewerwindow.o \
		procesadora.o \
		Mensaje.pb.o \
		moc_imagineviewerwindow.o \
		moc_procesadora.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		protobuf.pri \
		opencv.pri \
		QtOpenCV.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Capturas.pro
QMAKE_TARGET  = Capturas
DESTDIR       = 
TARGET        = Capturas

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_imagineviewerwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Capturas.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		protobuf.pri \
		opencv.pri \
		QtOpenCV.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Capturas.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
protobuf.pri:
opencv.pri:
QtOpenCV.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Capturas.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Capturas1.0.0 || $(MKDIR) .tmp/Capturas1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Capturas1.0.0/ && $(COPY_FILE) --parents Mensaje.proto .tmp/Capturas1.0.0/ && $(COPY_FILE) --parents Mensaje.proto .tmp/Capturas1.0.0/ && $(COPY_FILE) --parents cvmatandqimage.h imagineviewerwindow.h procesadora.h cvmatandqimage cvmatandqimage servidor.h .tmp/Capturas1.0.0/ && $(COPY_FILE) --parents cvmatandqimage.cpp main.cpp imagineviewerwindow.cpp procesadora.cpp .tmp/Capturas1.0.0/ && $(COPY_FILE) --parents imagineviewerwindow.ui .tmp/Capturas1.0.0/ && (cd `dirname .tmp/Capturas1.0.0` && $(TAR) Capturas1.0.0.tar Capturas1.0.0 && $(COMPRESS) Capturas1.0.0.tar) && $(MOVE) `dirname .tmp/Capturas1.0.0`/Capturas1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Capturas1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_protobuf_decl_make_all: Mensaje.pb.h
compiler_protobuf_decl_clean:
	-$(DEL_FILE) Mensaje.pb.h
Mensaje.pb.h: Mensaje.proto
	protoc --cpp_out=. --proto_path=. Mensaje.proto

compiler_protobuf_impl_make_all: Mensaje.pb.cc
compiler_protobuf_impl_clean:
	-$(DEL_FILE) Mensaje.pb.cc
Mensaje.pb.cc: Mensaje.proto \
		Mensaje.pb.h
	


compiler_moc_header_make_all: moc_imagineviewerwindow.cpp moc_procesadora.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_imagineviewerwindow.cpp moc_procesadora.cpp
moc_imagineviewerwindow.cpp: procesadora.h \
		Mensaje.pb.h \
		imagineviewerwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imagineviewerwindow.h -o moc_imagineviewerwindow.cpp

moc_procesadora.cpp: procesadora.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) procesadora.h -o moc_procesadora.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_imagineviewerwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_imagineviewerwindow.h
ui_imagineviewerwindow.h: imagineviewerwindow.ui
	/usr/bin/uic-qt4 imagineviewerwindow.ui -o ui_imagineviewerwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_protobuf_decl_clean compiler_protobuf_impl_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

cvmatandqimage.o: cvmatandqimage.cpp cvmatandqimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvmatandqimage.o cvmatandqimage.cpp

main.o: main.cpp imagineviewerwindow.h \
		procesadora.h \
		Mensaje.pb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

imagineviewerwindow.o: imagineviewerwindow.cpp imagineviewerwindow.h \
		procesadora.h \
		Mensaje.pb.h \
		ui_imagineviewerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagineviewerwindow.o imagineviewerwindow.cpp

procesadora.o: procesadora.cpp procesadora.h \
		cvmatandqimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o procesadora.o procesadora.cpp

Mensaje.pb.o: Mensaje.pb.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mensaje.pb.o Mensaje.pb.cc

moc_imagineviewerwindow.o: moc_imagineviewerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagineviewerwindow.o moc_imagineviewerwindow.cpp

moc_procesadora.o: moc_procesadora.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_procesadora.o moc_procesadora.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

