// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mensaje.proto

#ifndef PROTOBUF_Mensaje_2eproto__INCLUDED
#define PROTOBUF_Mensaje_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Mensaje_2eproto();
void protobuf_AssignDesc_Mensaje_2eproto();
void protobuf_ShutdownFile_Mensaje_2eproto();

class Mensaje;
class Mensaje_Rectangulo;

// ===================================================================

class Mensaje_Rectangulo : public ::google::protobuf::Message {
 public:
  Mensaje_Rectangulo();
  virtual ~Mensaje_Rectangulo();
  
  Mensaje_Rectangulo(const Mensaje_Rectangulo& from);
  
  inline Mensaje_Rectangulo& operator=(const Mensaje_Rectangulo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Mensaje_Rectangulo& default_instance();
  
  void Swap(Mensaje_Rectangulo* other);
  
  // implements Message ----------------------------------------------
  
  Mensaje_Rectangulo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Mensaje_Rectangulo& from);
  void MergeFrom(const Mensaje_Rectangulo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 X = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // required int32 Y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // required int32 ancho = 3;
  inline bool has_ancho() const;
  inline void clear_ancho();
  static const int kAnchoFieldNumber = 3;
  inline ::google::protobuf::int32 ancho() const;
  inline void set_ancho(::google::protobuf::int32 value);
  
  // required int32 alto = 4;
  inline bool has_alto() const;
  inline void clear_alto();
  static const int kAltoFieldNumber = 4;
  inline ::google::protobuf::int32 alto() const;
  inline void set_alto(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Mensaje.Rectangulo)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_ancho();
  inline void clear_has_ancho();
  inline void set_has_alto();
  inline void clear_has_alto();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 ancho_;
  ::google::protobuf::int32 alto_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Mensaje_2eproto();
  friend void protobuf_AssignDesc_Mensaje_2eproto();
  friend void protobuf_ShutdownFile_Mensaje_2eproto();
  
  void InitAsDefaultInstance();
  static Mensaje_Rectangulo* default_instance_;
};
// -------------------------------------------------------------------

class Mensaje : public ::google::protobuf::Message {
 public:
  Mensaje();
  virtual ~Mensaje();
  
  Mensaje(const Mensaje& from);
  
  inline Mensaje& operator=(const Mensaje& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Mensaje& default_instance();
  
  void Swap(Mensaje* other);
  
  // implements Message ----------------------------------------------
  
  Mensaje* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Mensaje& from);
  void MergeFrom(const Mensaje& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Mensaje_Rectangulo Rectangulo;
  
  // accessors -------------------------------------------------------
  
  // required string deviceName = 1;
  inline bool has_devicename() const;
  inline void clear_devicename();
  static const int kDeviceNameFieldNumber = 1;
  inline const ::std::string& devicename() const;
  inline void set_devicename(const ::std::string& value);
  inline void set_devicename(const char* value);
  inline void set_devicename(const char* value, size_t size);
  inline ::std::string* mutable_devicename();
  inline ::std::string* release_devicename();
  
  // required uint64 timestamp = 2;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  inline ::google::protobuf::uint64 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint64 value);
  
  // required bytes imagenes = 3;
  inline bool has_imagenes() const;
  inline void clear_imagenes();
  static const int kImagenesFieldNumber = 3;
  inline const ::std::string& imagenes() const;
  inline void set_imagenes(const ::std::string& value);
  inline void set_imagenes(const char* value);
  inline void set_imagenes(const void* value, size_t size);
  inline ::std::string* mutable_imagenes();
  inline ::std::string* release_imagenes();
  
  // repeated .Mensaje.Rectangulo rectangulos = 4;
  inline int rectangulos_size() const;
  inline void clear_rectangulos();
  static const int kRectangulosFieldNumber = 4;
  inline const ::Mensaje_Rectangulo& rectangulos(int index) const;
  inline ::Mensaje_Rectangulo* mutable_rectangulos(int index);
  inline ::Mensaje_Rectangulo* add_rectangulos();
  inline const ::google::protobuf::RepeatedPtrField< ::Mensaje_Rectangulo >&
      rectangulos() const;
  inline ::google::protobuf::RepeatedPtrField< ::Mensaje_Rectangulo >*
      mutable_rectangulos();
  
  // @@protoc_insertion_point(class_scope:Mensaje)
 private:
  inline void set_has_devicename();
  inline void clear_has_devicename();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_imagenes();
  inline void clear_has_imagenes();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* devicename_;
  ::google::protobuf::uint64 timestamp_;
  ::std::string* imagenes_;
  ::google::protobuf::RepeatedPtrField< ::Mensaje_Rectangulo > rectangulos_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Mensaje_2eproto();
  friend void protobuf_AssignDesc_Mensaje_2eproto();
  friend void protobuf_ShutdownFile_Mensaje_2eproto();
  
  void InitAsDefaultInstance();
  static Mensaje* default_instance_;
};
// ===================================================================


// ===================================================================

// Mensaje_Rectangulo

// required int32 X = 1;
inline bool Mensaje_Rectangulo::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Mensaje_Rectangulo::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Mensaje_Rectangulo::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Mensaje_Rectangulo::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Mensaje_Rectangulo::x() const {
  return x_;
}
inline void Mensaje_Rectangulo::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 Y = 2;
inline bool Mensaje_Rectangulo::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Mensaje_Rectangulo::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Mensaje_Rectangulo::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Mensaje_Rectangulo::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Mensaje_Rectangulo::y() const {
  return y_;
}
inline void Mensaje_Rectangulo::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// required int32 ancho = 3;
inline bool Mensaje_Rectangulo::has_ancho() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Mensaje_Rectangulo::set_has_ancho() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Mensaje_Rectangulo::clear_has_ancho() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Mensaje_Rectangulo::clear_ancho() {
  ancho_ = 0;
  clear_has_ancho();
}
inline ::google::protobuf::int32 Mensaje_Rectangulo::ancho() const {
  return ancho_;
}
inline void Mensaje_Rectangulo::set_ancho(::google::protobuf::int32 value) {
  set_has_ancho();
  ancho_ = value;
}

// required int32 alto = 4;
inline bool Mensaje_Rectangulo::has_alto() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Mensaje_Rectangulo::set_has_alto() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Mensaje_Rectangulo::clear_has_alto() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Mensaje_Rectangulo::clear_alto() {
  alto_ = 0;
  clear_has_alto();
}
inline ::google::protobuf::int32 Mensaje_Rectangulo::alto() const {
  return alto_;
}
inline void Mensaje_Rectangulo::set_alto(::google::protobuf::int32 value) {
  set_has_alto();
  alto_ = value;
}

// -------------------------------------------------------------------

// Mensaje

// required string deviceName = 1;
inline bool Mensaje::has_devicename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Mensaje::set_has_devicename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Mensaje::clear_has_devicename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Mensaje::clear_devicename() {
  if (devicename_ != &::google::protobuf::internal::kEmptyString) {
    devicename_->clear();
  }
  clear_has_devicename();
}
inline const ::std::string& Mensaje::devicename() const {
  return *devicename_;
}
inline void Mensaje::set_devicename(const ::std::string& value) {
  set_has_devicename();
  if (devicename_ == &::google::protobuf::internal::kEmptyString) {
    devicename_ = new ::std::string;
  }
  devicename_->assign(value);
}
inline void Mensaje::set_devicename(const char* value) {
  set_has_devicename();
  if (devicename_ == &::google::protobuf::internal::kEmptyString) {
    devicename_ = new ::std::string;
  }
  devicename_->assign(value);
}
inline void Mensaje::set_devicename(const char* value, size_t size) {
  set_has_devicename();
  if (devicename_ == &::google::protobuf::internal::kEmptyString) {
    devicename_ = new ::std::string;
  }
  devicename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Mensaje::mutable_devicename() {
  set_has_devicename();
  if (devicename_ == &::google::protobuf::internal::kEmptyString) {
    devicename_ = new ::std::string;
  }
  return devicename_;
}
inline ::std::string* Mensaje::release_devicename() {
  clear_has_devicename();
  if (devicename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = devicename_;
    devicename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint64 timestamp = 2;
inline bool Mensaje::has_timestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Mensaje::set_has_timestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Mensaje::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Mensaje::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 Mensaje::timestamp() const {
  return timestamp_;
}
inline void Mensaje::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// required bytes imagenes = 3;
inline bool Mensaje::has_imagenes() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Mensaje::set_has_imagenes() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Mensaje::clear_has_imagenes() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Mensaje::clear_imagenes() {
  if (imagenes_ != &::google::protobuf::internal::kEmptyString) {
    imagenes_->clear();
  }
  clear_has_imagenes();
}
inline const ::std::string& Mensaje::imagenes() const {
  return *imagenes_;
}
inline void Mensaje::set_imagenes(const ::std::string& value) {
  set_has_imagenes();
  if (imagenes_ == &::google::protobuf::internal::kEmptyString) {
    imagenes_ = new ::std::string;
  }
  imagenes_->assign(value);
}
inline void Mensaje::set_imagenes(const char* value) {
  set_has_imagenes();
  if (imagenes_ == &::google::protobuf::internal::kEmptyString) {
    imagenes_ = new ::std::string;
  }
  imagenes_->assign(value);
}
inline void Mensaje::set_imagenes(const void* value, size_t size) {
  set_has_imagenes();
  if (imagenes_ == &::google::protobuf::internal::kEmptyString) {
    imagenes_ = new ::std::string;
  }
  imagenes_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Mensaje::mutable_imagenes() {
  set_has_imagenes();
  if (imagenes_ == &::google::protobuf::internal::kEmptyString) {
    imagenes_ = new ::std::string;
  }
  return imagenes_;
}
inline ::std::string* Mensaje::release_imagenes() {
  clear_has_imagenes();
  if (imagenes_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = imagenes_;
    imagenes_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Mensaje.Rectangulo rectangulos = 4;
inline int Mensaje::rectangulos_size() const {
  return rectangulos_.size();
}
inline void Mensaje::clear_rectangulos() {
  rectangulos_.Clear();
}
inline const ::Mensaje_Rectangulo& Mensaje::rectangulos(int index) const {
  return rectangulos_.Get(index);
}
inline ::Mensaje_Rectangulo* Mensaje::mutable_rectangulos(int index) {
  return rectangulos_.Mutable(index);
}
inline ::Mensaje_Rectangulo* Mensaje::add_rectangulos() {
  return rectangulos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Mensaje_Rectangulo >&
Mensaje::rectangulos() const {
  return rectangulos_;
}
inline ::google::protobuf::RepeatedPtrField< ::Mensaje_Rectangulo >*
Mensaje::mutable_rectangulos() {
  return &rectangulos_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Mensaje_2eproto__INCLUDED
